#!/usr/bin/env bash
# SDD ship script.
# Pushes the active feature branch, opens/updates its PR, watches CI,
# and either marks the feature SHIPPED or captures a bug task.
#
# Prerequisites:
#   - gh CLI authenticated (`gh auth status`)
#   - Active feature in .sdd/INDEX.md, spec in phase VERIFY with all gates passed
#   - Remote `origin` configured

set -euo pipefail

# ─── Preconditions ──────────────────────────────────────────────────

if [ ! -d .sdd ]; then
  echo "ERROR: .sdd/ not found. Are you at the project root?" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: gh CLI not found. Install from https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh not authenticated. Run: gh auth login" >&2
  exit 1
fi

# Resolve active feature
active=$(grep -m1 -E '^\*\*Active:\*\*' .sdd/INDEX.md | grep -oE 'features/[A-Za-z0-9._-]+' | head -1 || echo "")
if [ -z "$active" ]; then
  echo "ERROR: no active feature in .sdd/INDEX.md" >&2
  exit 1
fi

spec=".sdd/$active/spec.md"
if [ ! -f "$spec" ]; then
  echo "ERROR: $spec not found" >&2
  exit 1
fi

phase=$(grep -m1 -oE '\[PHASE: [A-Z]+\]' "$spec" | grep -oE '[A-Z]+' | tail -1)
if [ "$phase" != "VERIFY" ] && [ "$phase" != "LEARN" ]; then
  echo "ERROR: active feature is in phase $phase. /ship expects VERIFY (all tests green) or LEARN." >&2
  echo "       Run /verify first, or manually flip the phase if you know what you're doing." >&2
  exit 1
fi

# Derive branch and feature id
feature_id="${active#features/}"
branch="sdd/$feature_id"

# Dirty tree check
if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree is dirty. Commit or stash changes first." >&2
  git status --short
  exit 1
fi

# ─── Push ───────────────────────────────────────────────────────────

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "$branch" ]; then
  echo "WARN: current branch is '$current_branch', expected '$branch'." >&2
  echo "       Checking out $branch…" >&2
  git checkout "$branch" 2>/dev/null || {
    echo "ERROR: could not check out $branch. Create it first: git checkout -b $branch" >&2
    exit 1
  }
fi

echo "→ Pushing $branch to origin…"
git push -u origin "$branch"

# ─── Create or update PR ────────────────────────────────────────────

# Extract feature name from spec.md first heading
feature_name=$(grep -m1 -E '^# Feature:' "$spec" | sed 's/^# Feature:[[:space:]]*//' | sed 's/[[:space:]]*\[PHASE:.*$//')

# Build a PR body: short summary + link to spec, plus the spec itself (folded).
pr_body=$(cat <<EOF
## What this ships
$feature_name

## Spec
Full spec lives at \`$spec\` in this branch. Summary below.

<details>
<summary>Click to expand spec.md</summary>

$(cat "$spec")

</details>

## Sign-off status
See Section 11 of the spec. Human sign-off must be ticked before merge.

—
🤖 Generated by \`/ship\` (SDD workflow)
EOF
)

# Does the PR already exist?
pr_number=$(gh pr view --json number --jq .number 2>/dev/null || echo "")

if [ -z "$pr_number" ]; then
  echo "→ Creating PR…"
  gh pr create --title "[SDD:$feature_id] $feature_name" --body "$pr_body" --base main --head "$branch"
  pr_number=$(gh pr view --json number --jq .number)
else
  echo "→ Updating PR #$pr_number…"
  gh pr edit "$pr_number" --body "$pr_body"
fi

pr_url=$(gh pr view "$pr_number" --json url --jq .url)
echo "   PR: $pr_url"

# ─── Watch CI ───────────────────────────────────────────────────────

echo "→ Watching CI (gh pr checks --watch)…"
set +e
gh pr checks "$pr_number" --watch
ci_exit=$?
set -e

# ─── Outcome ────────────────────────────────────────────────────────

if [ $ci_exit -eq 0 ]; then
  echo "✓ CI passed."

  # Mark feature SHIPPED in INDEX.md.
  # Clear the Active pointer and append to Shipped section.
  today=$(date +%Y-%m-%d)
  python3 - "$active" "$pr_url" "$today" <<'PY'
import re, sys, pathlib
active, pr_url, today = sys.argv[1], sys.argv[2], sys.argv[3]
idx = pathlib.Path(".sdd/INDEX.md")
text = idx.read_text()

# Clear Active pointer
text = re.sub(r"(\*\*Active:\*\*).*", r"\1 _(none)_", text, count=1)

# Append to Shipped section
shipped_line = f"- {active} — {pr_url} — merged {today}"
if re.search(r"^## Shipped\s*$", text, flags=re.MULTILINE):
    text = re.sub(
        r"(## Shipped\s*\n(?:<!--[\s\S]*?-->\s*\n)?\s*)(_\(empty\)_|\n)?",
        lambda m: m.group(1) + shipped_line + "\n",
        text,
        count=1,
    )

# Remove the feature from "In flight" if present
text = re.sub(rf"(?m)^- {re.escape(active)}.*\n", "", text)

idx.write_text(text)
PY

  # Flip phase in spec.md to LEARN (or SHIPPED — we use LEARN so the user can capture lessons first)
  sed -i.bak -E 's/\[PHASE: [A-Z]+\]/[PHASE: LEARN]/' "$spec" && rm -f "$spec.bak"

  git add .sdd/INDEX.md "$spec"
  git commit -m "[SDD:$feature_id] ship: CI green, marked for LEARN" || true
  git push

  echo ""
  echo "Next: capture lessons in Section LEARN of the spec, then merge the PR on GitHub."
  echo "PR: $pr_url"
  exit 0
else
  echo "✗ CI failed."

  # Capture the failed check summary
  fail_log=$(gh pr checks "$pr_number" --watch=false 2>&1 | grep -E 'fail|✗' || echo "(no summary captured)")

  # Append a bug task to the PLAN section of spec.md
  # Flip phase back to BUILD
  bug_summary=$(echo "$fail_log" | head -3 | tr '\n' '; ' | head -c 200)

  python3 - "$spec" "$bug_summary" <<'PY'
import sys, pathlib, re
spec_path, summary = sys.argv[1], sys.argv[2]
p = pathlib.Path(spec_path)
text = p.read_text()

# Flip phase
text = re.sub(r"\[PHASE: [A-Z]+\]", "[PHASE: BUILD]", text, count=1)

# Append bug task under "## PHASE: PLAN" → Tasks section
bug_line = f"- [ ] bug: CI failed on ship — {summary}   status: RED"
if "## PHASE: PLAN" in text:
    # Find the Tasks subsection within PLAN
    text = re.sub(
        r"(## PHASE: PLAN[\s\S]*?### Tasks[\s\S]*?\n)",
        lambda m: m.group(1) + bug_line + "\n",
        text,
        count=1,
    )
else:
    text += "\n\n<!-- bug task appended by /ship on CI failure -->\n" + bug_line + "\n"

p.write_text(text)
PY

  git add "$spec"
  git commit -m "[SDD:$feature_id][BUG] ship: CI failed, bug task appended"
  git push

  echo ""
  echo "Next: run /next to work the bug task."
  echo "PR: $pr_url"
  exit 1
fi
