#!/usr/bin/env bash
# SDD ship script.
# Pushes the active feature branch, opens/updates its PR, watches CI,
# and either marks the feature SHIPPED or captures a bug task.
#
# Prerequisites:
#   - gh CLI authenticated (`gh auth status`)
#   - Active feature in .sdd/INDEX.md, spec in phase VERIFY with all gates passed
#   - Remote `origin` configured

set -euo pipefail

# ─── Preconditions ──────────────────────────────────────────────────

if [ ! -d .sdd ]; then
  echo "ERROR: .sdd/ not found. Are you at the project root?" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: gh CLI not found. Install from https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh not authenticated. Run: gh auth login" >&2
  exit 1
fi

# Resolve active feature
active=$(grep -m1 -E '^\*\*Active:\*\*' .sdd/INDEX.md | grep -oE 'features/[A-Za-z0-9._-]+' | head -1 || echo "")
if [ -z "$active" ]; then
  echo "ERROR: no active feature in .sdd/INDEX.md" >&2
  exit 1
fi

spec=".sdd/$active/spec.md"
if [ ! -f "$spec" ]; then
  echo "ERROR: $spec not found" >&2
  exit 1
fi

phase=$(grep -m1 -oE '\[PHASE: [A-Z]+\]' "$spec" | grep -oE '[A-Z]+' | tail -1)
# v0.8 3-phase spine: SPEC → BUILD → SHIP. The legacy VERIFY/LEARN phases
# are now sub-actions of SHIP (verify-test-run, verify-prod-only-acs,
# learn-summary, learn-lessons). /ship runs once the SHIP phase has been
# reached — its sub-actions take it the rest of the way.
if [ "$phase" != "SHIP" ]; then
  echo "ERROR: active work item is in phase $phase. /ship expects SHIP (the v0.8 final phase)." >&2
  echo "       Run /next until you've completed BUILD and reached SHIP, then /ship." >&2
  exit 1
fi

# Derive branch and feature id (path-generic — strips any folder prefix
# like features/, bugs/, ideas/ to leave just the <id>-<slug> for the
# branch name, matching the convention sdd/<id>-<slug>).
feature_id="${active##*/}"
branch="sdd/$feature_id"

# Dirty tree check
if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree is dirty. Commit or stash changes first." >&2
  git status --short
  exit 1
fi

# ─── Push ───────────────────────────────────────────────────────────

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "$branch" ]; then
  echo "WARN: current branch is '$current_branch', expected '$branch'." >&2
  echo "       Checking out $branch…" >&2
  git checkout "$branch" 2>/dev/null || {
    echo "ERROR: could not check out $branch. Create it first: git checkout -b $branch" >&2
    exit 1
  }
fi

echo "→ Pushing $branch to origin…"
git push -u origin "$branch"

# ─── Create or update PR ────────────────────────────────────────────

# Extract feature name from spec.md first heading
feature_name=$(grep -m1 -E '^# Feature:' "$spec" | sed 's/^# Feature:[[:space:]]*//' | sed 's/[[:space:]]*\[PHASE:.*$//')

# Build a PR body: short summary + link to spec, plus the spec itself (folded).
pr_body=$(cat <<EOF
## What this ships
$feature_name

## Spec
Full spec lives at \`$spec\` in this branch. Summary below.

<details>
<summary>Click to expand spec.md</summary>

$(cat "$spec")

</details>

## Sign-off status
See Section 11 of the spec. Human sign-off must be ticked before merge.

—
🤖 Generated by \`/ship\` (SDD workflow)
EOF
)

# Does the PR already exist?
pr_number=$(gh pr view --json number --jq .number 2>/dev/null || echo "")

if [ -z "$pr_number" ]; then
  echo "→ Creating PR…"
  gh pr create --title "[SDD:$feature_id] $feature_name" --body "$pr_body" --base main --head "$branch"
  pr_number=$(gh pr view --json number --jq .number)
else
  echo "→ Updating PR #$pr_number…"
  gh pr edit "$pr_number" --body "$pr_body"
fi

pr_url=$(gh pr view "$pr_number" --json url --jq .url)
echo "   PR: $pr_url"

# ─── Watch CI ───────────────────────────────────────────────────────

echo "→ Watching CI (gh pr checks --watch)…"
set +e
gh pr checks "$pr_number" --watch
ci_exit=$?
set -e

# ─── Outcome ────────────────────────────────────────────────────────

if [ $ci_exit -eq 0 ]; then
  echo "✓ CI passed."

  # ─── Distillation: extract one-line summary from spec's "What shipped" / §1 ───
  today=$(date +%Y-%m-%d)
  one_liner=$(awk '
    /^### What shipped/ {flag=1; next}
    flag && /^- / && !/^- \[ \]/ {sub(/^- /, ""); print; exit}
    flag && /^### / {flag=0}
  ' "$spec" 2>/dev/null | head -c 140)
  if [ -z "$one_liner" ]; then
    one_liner=$(grep -A 10 '### 1\. Problem' "$spec" 2>/dev/null | grep -m1 -E 'Who has it|What breaks' | sed -E 's/^[*-]\s*\*\*[^:]+:\*\*\s*//' | head -c 140)
  fi
  [ -z "$one_liner" ] && one_liner="(see $spec for details)"

  # Mark feature SHIPPED in INDEX.md
  python3 - "$active" "$pr_url" "$today" "$one_liner" <<'PY'
import re, sys, pathlib
active, pr_url, today, one_liner = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
idx = pathlib.Path(".sdd/INDEX.md")
text = idx.read_text()

text = re.sub(r"(\*\*Active:\*\*).*", r"\1 _(none)_", text, count=1)

shipped_line = f"- {active} — {pr_url} — merged {today} — {one_liner}"
if re.search(r"^## Shipped\s*$", text, flags=re.MULTILINE):
    text = re.sub(
        r"(## Shipped[\s\S]*?\n(?:<!--[\s\S]*?-->\s*\n)?\s*)(_\(empty\)_\s*\n)?",
        lambda m: m.group(1) + shipped_line + "\n",
        text,
        count=1,
    )

text = re.sub(rf"(?m)^- {re.escape(active)}.*\n", "", text)

idx.write_text(text)
PY

  # Cold-tier marker: shipped feature folder gets a .shipped file. Agents read it as
  # "do not load this spec.md unless explicitly asked".
  touch ".sdd/$active/.shipped"

  # Surface [PROD-ONLY] ACs into the "Pending production verification" block in INDEX.
  python3 - "$active" "$spec" <<'PY'
import re, sys, pathlib
active, spec_path = sys.argv[1], sys.argv[2]
spec_text = pathlib.Path(spec_path).read_text()
prod_acs = re.findall(r'^[\s-]*\[ ?[xX ]? ?\]\s*(AC\d+:.*\[PROD-ONLY\].*)$', spec_text, flags=re.MULTILINE)
if not prod_acs:
    sys.exit(0)
idx = pathlib.Path(".sdd/INDEX.md")
text = idx.read_text()
lines = "\n".join(f"- {active} — [ ] {ac.strip()}" for ac in prod_acs)
if "## Pending production verification" in text:
    text = re.sub(
        r"(### Pending production verification[\s\S]*?\n(?:<!--[\s\S]*?-->\s*\n)?\s*)(_\(none\)_\s*\n)?",
        lambda m: m.group(1) + lines + "\n",
        text,
        count=1,
    )
    idx.write_text(text)
PY

  # v0.8: stay in SHIP phase — the learn-summary / learn-lessons
  # sub-actions inside SHIP capture lessons. No phase-flip needed; the
  # remaining SHIP sub-actions complete via /next.

  # Size-cap nudge — print a notice if patterns.md or INDEX.md crossed thresholds
  patterns_lines=$(wc -l < .sdd/patterns.md 2>/dev/null | tr -d ' ' || echo 0)
  index_lines=$(wc -l < .sdd/INDEX.md | tr -d ' ')
  echo ""
  if [ "$patterns_lines" -ge 250 ]; then
    echo "  (notice) .sdd/patterns.md is now $patterns_lines lines — consider /compress patterns soon."
  fi
  if [ "$index_lines" -ge 200 ]; then
    echo "  (notice) .sdd/INDEX.md is now $index_lines lines — old shipped entries should rotate to .sdd/archive/."
  fi

  git add .sdd/INDEX.md "$spec" ".sdd/$active/.shipped"
  # CodeRabbit cycle 9/10/11: drop the `|| true` swallowing commit
  # failures. If the commit fails (hook block, no diff, etc.) the
  # script should fail loud — silent success would push an empty
  # branch state to remote and confuse the user.
  git commit -m "[SDD:$feature_id] ship: CI green; spec marked cold (.shipped)"
  git push

  echo ""
  echo "Next: run /next to capture lessons via the learn-summary + learn-lessons"
  echo "      sub-actions, then merge the PR on GitHub."
  echo "  Spec is now cold — agent will not re-read it unless you reference it explicitly."
  echo "PR: $pr_url"
  exit 0
else
  echo "✗ CI failed."

  # Capture the failed check summary
  fail_log=$(gh pr checks "$pr_number" --watch=false 2>&1 | grep -E 'fail|✗' || echo "(no summary captured)")

  # Append a bug task to the BUILD section of spec.md and flip phase back to BUILD
  # (v0.8: tasks live inside ## PHASE: BUILD; in Phase A they lived inside PLAN).
  bug_summary=$(echo "$fail_log" | head -3 | tr '\n' '; ' | head -c 200)

  python3 - "$spec" "$bug_summary" <<'PY'
import sys, pathlib, re
spec_path, summary = sys.argv[1], sys.argv[2]
p = pathlib.Path(spec_path)
text = p.read_text()

# Flip phase back to BUILD so /next picks up the new bug task
text = re.sub(r"\[PHASE: [A-Z]+\]", "[PHASE: BUILD]", text, count=1)

# Append bug task under "## PHASE: BUILD" → Tasks section
bug_line = f"- [ ] bug: CI failed on ship — {summary}   status: RED"
if "## PHASE: BUILD" in text:
    # Find the Tasks subsection within BUILD (or fall back to end of section)
    if re.search(r"## PHASE: BUILD[\s\S]*?### Tasks", text):
        text = re.sub(
            r"(## PHASE: BUILD[\s\S]*?### Tasks[\s\S]*?\n)",
            lambda m: m.group(1) + bug_line + "\n",
            text,
            count=1,
        )
    else:
        # No ### Tasks subsection — append after the BUILD heading line
        text = re.sub(
            r"(## PHASE: BUILD\n)",
            lambda m: m.group(1) + "\n### Tasks\n\n" + bug_line + "\n",
            text,
            count=1,
        )
else:
    text += "\n\n<!-- bug task appended by /ship on CI failure -->\n" + bug_line + "\n"

p.write_text(text)
PY

  git add "$spec"
  git commit -m "[SDD:$feature_id][BUG] ship: CI failed, bug task appended"
  git push

  echo ""
  echo "Next: run /next to work the bug task."
  echo "PR: $pr_url"
  exit 1
fi
